application: susanandmatthewwebsite
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.+)
  static_files: application_folder/\1 
  upload: application_folder/(.+) 

- url: /
  static_files: application_folder/index.html
  upload: application_folder/index.html



